### ISSUE TITLE
[Generator] GameTDB artworks are not always under the correct region

### ISSUE THREAD

**Issue by CommandMC** [YANBForwarder/YANBF#19] opened 2022-04-24 19:16 UTC
I'm currently using YANBF to create forwarders to some German games, however, the artwork detection fails for those. There are some pretty popular games in the list (4th gen Pokémon for example), so I'm pretty sure artwork is available (oh actually, it's able to find artwork for Pokémon Pearl since that's named the same over here, so I guess that confirms it).
As far as I know, DS games have a Game ID of some sorts? Would it be possible to match artwork based on that?

**Comment by CommandMC** [comment] 2022-04-24 19:28
Hm, actually, it seems like Pokémon Black and White were detected fine even though they have localized names.

In case it helps, here are the SHA1s of the problematic NDS files:
| English Name | Localized Name | SHA1 |
| --- | --- | --- |
| Pokémon Diamond | Pokémon Diamant | `432dbe312bc51e36bb8cb6fcb5e08f6968f124a4` |
| Pokémon Platinum | Pokémon Platin | `d40f19ac24d67c721a4ab25e1c013154443d75b4` |
| *Unknown, not sure if this even got an international release* | Bibi Blocksberg - Der verhexte Schloss-Schatz | `e5e8ab52f706e9f536ed69de1893e3963842540e` |

**Comment by lifehackerhansol** [comment] 2022-04-24 19:59
The artwork is not checked by the titles. It's done by the ROM header, which doubles as the serial number used to contact [GameTDB](https://gametdb.com)'s API. 

For some reason, Diamond and Platinum (and other Poke titles for that matter) appear to be in the `EN` database. Which brings to question whether there is a `DE` endpoint in the first place...?

That being said, can you get the serials for games with the issues? i.e. `NTR-IPKE-USA`

**Comment by CommandMC** [comment] 2022-04-24 20:06
Thanks for the quick reply
The serials are the following:
| Game | Serial |
| --- | --- |
| Pokémon Diamond | NTR-ADAD-NOE |
| Pokémon Platinum | NTR-CPUD-NOE |
| Bibi Blocksberg - Der verhexte Schloss-Schatz | NTR-TBLD-NOE |

I've also cloned the `assets` repo and am currently working on a banner for that 3rd game (since I assume you guys don't have it yet?)

**Comment by lifehackerhansol** [comment] 2022-04-24 20:18
After some digging, it seems some games are under the wrong location.

For example, this is how GameTDB's URLs work: you have `http://art.gametdb.com/<insert region here>/<insert game ID here>.jpg`

The problem is that several games I tested in German should be under `http://art.gametdb.com/DE/<insert game ID here>.jpg`, however it is instead under `http://art.gametdb.com/EN/`. Why they have German stuff under the English section, I don't know, but for now I don't really have a workaround.

I suppose I could have the program test all languages until it finds it, but I really don't want to spam their servers like that. So for now I've reported it to GameTDB in their forum thread [here](https://gbatemp.net/threads/gametdb-game-information-database-covers.164945/post-9809404).

**Comment by CommandMC** [comment] 2022-04-24 20:25
> I suppose I could have the program test all languages until it finds it, but I really don't want to spam their servers like that.

Could test just the EN URL.  
One extra server request for some specific games doesn't sound like that bad of an idea

**Comment by lifehackerhansol** [comment] 2022-04-24 20:46
I'll look into it. It seems EN would be the logical choice of testing. Just makes me wonder if that's the be-all-end-all solution. But I guess if it works then *shrug*

**Comment by lifehackerhansol** [comment] 2022-04-24 21:03
I've added the function to check EN if not found the first time. Can you test? https://nightly.link/YANBForwarder/YANBF/workflows/nightly/main/YANBF-Windows.zip

It worked on my end for a certain title that also had this behaviour.

**Comment by CommandMC** [comment] 2022-04-24 21:05
I was just about to test it
Btw, the `linux` workflow names its files `macOS`. Relevant line is [this](https://github.com/YANBForwarder/YANBF/blob/main/.github/workflows/nightly.yml#L153)

**Comment by lifehackerhansol** [comment] 2022-04-24 21:06
God damn it, I thought I fixed this (apparently I only fixed the release...)

**Comment by CommandMC** [comment] 2022-04-24 21:07
![image](https://user-images.githubusercontent.com/34034631/164996585-a99b1d57-4b69-45ef-9198-982bcf05bcbd.png)
Works :+1:

**Comment by lifehackerhansol** [comment] 2022-04-24 21:08
Fixed in commit a17094ef92965dbd68541f2164f59c2adcc856fc.

**Closed by lifehackerhansol** 2022-04-24 21:08 UTC
Labels: help wanted
