### ISSUE TITLE
Server-side SSL error after VPS switch

### ISSUE THREAD

**Issue by errorsxp** [YANBForwarder/YANBF#42] opened 2022-11-28 21:03 UTC
I used the program to make a forward yesterday, and it worked. I went back to make more today, and now the program hangs with this error displayed in the log.
"ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)"
I did everything the same way I did it yesterday, with the same file and output location (the ROM being on the SD card).
I'd appreciate some help with this!
Windows 10 Home x64 Latest Version

**Comment by lifehackerhansol** [comment] 2022-11-28 21:05
Alright so what actually happened is that my website shit itself. Currently I have it running on a new server.

Have you tried clearing your DNS cache on this computer?

**Comment by errorsxp** [comment] 2022-11-28 21:28
I just tried that but unfortunately it didn't work.

**Comment by lifehackerhansol** [comment] 2022-11-28 22:11
Does setting a different DNS server work? i.e. Google's 8.8.8.8/8.8.4.4?

I'll also test later today. I really don't know if this is a server problem though...

**Comment by lifehackerhansol** [comment] 2022-11-28 22:12
I really should figure out a local generation system.

**Comment by errorsxp** [comment] 2022-11-28 22:26
I couldn't get it to work after using Google's DNS server.
Is it possible to provide a download to all the content or have us pick what to download from a file hoster like Google Drive so we could do it locally?

**Comment by errorsxp** [comment] 2022-11-29 03:01
I tried setting my own sound and boxart. Does it still need to connect to the server?

**Comment by lifehackerhansol** [comment] 2022-11-29 03:14
It does not. At least, it is not supposed to.

Does it? Because that is something I need to fix.

I will work on a fully offline solution as well. But let me know if it continues to complain even with offline sound and banner.

**Comment by errorsxp** [comment] 2022-11-29 03:20
It may be trying to connect to the server since it still hangs when I set my own sound and boxart.

**Comment by lifehackerhansol** [comment] 2022-11-29 03:21
I will try to hotfix this in a moment and let you know of the results.

**Comment by lifehackerhansol** [comment] 2022-11-29 03:43
In about the next 5 minutes from this message, please download https://nightly.link/YANBForwarder/YANBF/workflows/nightly/main and see if it is working.

I have completely removed dependency from the API, but not yet of the Internet entirely. It's a band-aid solution, but I think it is for the best.

I'll also need to test the web still being called, which is coming after this.

**Comment by errorsxp** [comment] 2022-11-29 03:45
Alright, I'll try it when it's up.

**Comment by lifehackerhansol** [comment] 2022-11-29 04:19
Yeah ok I give up.

I manually built the Windows stuff. GitHub flatly refuses to cooperate with me today. 

To use this, extract this zip, then just copy the GUI.exe into the same folder. See if it works.
[generator-windows.zip](https://github.com/YANBForwarder/YANBF/files/10109673/generator-windows.zip)

**Comment by errorsxp** [comment] 2022-11-29 04:27
It's still hanging for me.

**Comment by lifehackerhansol** [comment] 2022-11-29 04:30
Sorry, it turns out I got my steps wrong. In the GUI you need to adjust the `Generator directory` to the location where the new `generator.exe` is.

Or you can try command-line directly.

**Comment by errorsxp** [comment] 2022-11-29 04:34
I'll try that. Also, I've noticed that when I try to set the generator directory by clicking on the select folder button, it doesn't replace it.

**Comment by lifehackerhansol** [comment] 2022-11-29 04:35
It seems to change on my end. Maybe path name is too long and doesn't show properly?

It would be nice to be able to scroll the text there, though. I'll look at that at a future date.

**Comment by errorsxp** [comment] 2022-11-29 04:41
I ran it and got this error now:
`FileNotFoundError: [Errno 2] No such file or directory: 'data/icon.png'
`
I tried to fix that by adding the image to the root of the generator and also renaming it to icon.png but I still get that error.

**Comment by lifehackerhansol** [comment] 2022-11-29 04:46
oh, oops. You need to copy the `data` folder over from the regular version. 

sorry this debugging is taking a while. Usually GitHub does it for me, but this week seems to be a ton of random crap thrown at once.

**Comment by errorsxp** [comment] 2022-11-29 04:51
I got this error and a subsequent one for 'makerom'. I know I need to copy over the .exe but just letting you know.
`'bannertool' is not recognized as an internal or external command,
operable program or batch file.
`
Also, I'm glad to help you fix this!

**Comment by errorsxp** [comment] 2022-11-29 04:55
The .cia generation works now, but when I installed it through FBI on my console, it didn't show up in the home menu.

**Comment by lifehackerhansol** [comment] 2022-11-29 04:58
Well, the CIA generation at least works, so that's a relief.

YANBF avoids conflicts with other YANBF forwarders via the use of a locally-recorded number of CIAs that were generated. Since we tested this on a new folder, and didn't copy `id.txt` over, what likely happened is that this CIA replaced the first YANBF-based forwarder you ever installed. 

Perhaps I need to keep a record of which ID corresponds to which, just to give the user a peace of mind.

**Comment by errorsxp** [comment] 2022-11-29 05:00
I noticed that the log file shows this:
`  File "C:\Users\lifehackerhansol\AppData\Local\Programs\Python\Python310\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 138, in run`
Is it supposed to be like that? In the previous log file from before this debugging (and it was working yesterday) that line would say:
`  File "C:\hostedtoolcache\windows\Python\3.10.7\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 120, in run`

**Comment by lifehackerhansol** [comment] 2022-11-29 05:02
Yes. Due to the nature of building an exe from python, sometimes it leaves traces of where the Python packages were installed in the machine that created it.

The second line resembles GitHub Actions's install location. The first line is my personal computer's install location, since GitHub Actions was not behaving and I had to do the work myself.

**Comment by errorsxp** [comment] 2022-11-29 05:04
> Well, the CIA generation at least works, so that's a relief.
> 
> YANBF avoids conflicts with other YANBF forwarders via the use of a locally-recorded number of CIAs that were generated. Since we tested this on a new folder, and didn't copy `id.txt` over, what likely happened is that this CIA replaced the first YANBF-based forwarder you ever installed.
> 
> Perhaps I need to keep a record of which ID corresponds to which, just to give the user a peace of mind.

You were right about this. I loaded up the forwarder I sucessfully installed yesterday and it booted into the game the new forwarder was meant for. Would I be able to run YANBF again to keep my original forwarder or will the id.txt not count it again since it's the same?

**Comment by lifehackerhansol** [comment] 2022-11-29 05:06
You can delete the new id.txt, and recreate the first game that it was intended to be, so it goes back to normal.

Then you can replace the new id.txt with the old id.txt file, and then recreate any new forwarder, and it will be back to regular counting.

**Comment by errorsxp** [comment] 2022-11-29 05:09
Alright! Is anything else needed?

**Comment by lifehackerhansol** [comment] 2022-11-29 05:12
As far as fixing the issues go, this is fixed by, ah, _removing the server._ It seems to generate fine on your end (as well as mine), so I will consider the issue closed.

Based on discussion in this server, I've seen things that could be improved with the program, and I will work on those in the meantime.

Thank you for being patient and testing with me on all of this.

**Closed by lifehackerhansol** 2022-11-29 05:12 UTC
Labels: help wanted
