### ISSUE TITLE
endless loading

### ISSUE THREAD

**Issue by kalebplayz125** [YANBForwarder/YANBF#12] opened 2022-03-29 23:03 UTC
the yanbf gui is endlessly loads

**Comment by Vent47** [comment] 2022-04-25 17:05
I have the same problem and can't get it to work 

![image](https://user-images.githubusercontent.com/92400243/165138310-b69f8092-106e-48ba-a6bf-3566eba2db5f.png)

**Comment by spitzeqc** [comment] 2022-04-29 18:18
This seems to be caused by a broken version of generator.exe packaged with v1.5.1 and v1.5.2. Using generator.exe from v1.5.0 seems to fix this issue

**Comment by lifehackerhansol** [comment] 2022-04-29 18:40
The only change is that I changed how generator.exe was created, which was supposed to avoid being flagged as malware.

I can't reproduce this. Can someone test the CLI manually and see where it's losing it?

**Comment by Vent47** [comment] 2022-04-30 13:31
> This seems to be caused by a broken version of generator.exe packaged with v1.5.1 and v1.5.2. Using generator.exe from v1.5.0 seems to fix this issue

I've used both 1.5.0 and 1.4.0 and none of them work. It may be the roms im using even though I've used 4 different ones.

I don't really know how i can help figure out what's wrong as i don't really know how any of this works but if it helps these are some of the roms i've been using

https://wowroms.com/es/roms/nintendo-ds/pokemon-mystery-dungeon-explorers-of-sky/19398.html
https://www.emulatorgames.net/roms/nintendo-ds/pokemon-mystery-dungeon-explorers-of-sky-us/
https://wowroms.com/en/roms/nintendo-ds/pokemon-mystery-dungeon-explorers-of-sky/19397.html

**Comment by Vent47** [comment] 2022-05-10 15:34
If by command-line program you mean the other exes I tried to run them and makerom doesn't open a console but appears for a second in the task bar, generator opens a console for a second without anything in it and closes and bannertool opens a console that says something that goes so fast I can't read it and closes. I also tried dragging a rom into them and the results were the same

**Comment by lifehackerhansol** [comment] 2022-05-10 19:44
That's expected behaviour. After all, it's a command-line program, so you need to open the command prompt and type in commands directly.

I have a guide on using just the command line on the README.

**Comment by Vent47** [comment] 2022-05-10 20:45
I just did that and it did the same thing as before and no CIA appeared on the cias folder

the command I used was: "start generator.exe <location of the rom>" on the windows cmd

**Comment by lifehackerhansol** [comment] 2022-05-10 20:49
The command is `generator.exe <your ROM>`

I don't know where the start came from.

**Comment by Vent47** [comment] 2022-05-10 21:10
I tried that and now it says it can't find a box art and a CIA didn't appear again

**Comment by lifehackerhansol** [comment] 2022-05-10 21:33
Now that you mention it, I wonder if it's the box art that's the issue. Which should be fixed in the next version.

Stay tuned.

**Comment by lifehackerhansol** [comment] 2022-05-11 02:12
Please test 1.6.0. Either GUI or CLI works.

**Comment by lifehackerhansol** [comment] 2022-05-11 16:41
Does the loading still circle forever? If not, then the banner stuff should be a separate issue.

**Comment by Vent47** [comment] 2022-05-11 19:14
It doesn't load forever now, it just shows this

![image](https://user-images.githubusercontent.com/92400243/167927899-b8ac7019-25b9-4565-8ad5-e1796598aad4.png)

**Comment by lifehackerhansol** [comment] 2022-05-12 21:06
@Vent47 what OS are you on, Windows, macOS, Linux? And what version?

**Comment by Vent47** [comment] 2022-05-12 21:19
I'm on Windows 10

**Comment by lifehackerhansol** [comment] 2022-05-12 21:23
Discussion moved to issue #25. 

The endless loading issue I will deem fixed. @Vent47 your issue is more relevant to the new one.

**Closed by lifehackerhansol** 2022-05-12 21:23 UTC
Labels: help wanted, question
